### ISSUE TITLE
Uncaught Error: MD5 password auth not implemented.

### ISSUE THREAD

**Issue by runnerSnail** [bartlomieju/deno-postgres#56] opened 2019-06-16 08:24 UTC
![image](https://user-images.githubusercontent.com/40654631/59561457-23decc80-9053-11e9-8c43-1589f418e32e.png)
![image](https://user-images.githubusercontent.com/40654631/59561467-47a21280-9053-11e9-9634-b6975513a888.png)

**Comment by bartlomieju** [comment] 2019-06-16 10:55
Duplicate of #4

**Closed by bartlomieju** 2019-06-16 10:55 UTC

**Comment by bartlomieju** [comment] 2019-06-16 11:38
FYI md5 password is available on `master` and via `v0.2.0` (https://deno.land/x/postgres@v0.2.0/mod.ts) tag.
